---
- name: Find EPG intent files
  ansible.builtin.find:
    paths: "{{ tenant_dir }}/application_profiles"
    patterns: "*.yml"
    recurse: true
    excludes: "profile.yml"
  register: epg_files
  delegate_to: localhost
  when: target_file | length == 0

- name: Set EPG file list (scoped)
  ansible.builtin.set_fact:
    epg_files:
      files:
        - path: "{{ playbook_dir }}/../{{ target_file }}"
  when: target_file | length > 0 and scoped_type == 'epgs'

- name: Apply each EPG
  ansible.builtin.include_tasks: _apply_epg.yml
  loop: "{{ epg_files.files | map(attribute='path') | list }}"
  loop_control:
    loop_var: epg_file
  when: epg_files.files | length > 0
