---
- name: Configure tenant
  cisco.aci.aci_tenant:
    host:           "{{ ansible_host }}"
    username:       "{{ ansible_user }}"
    password:       "{{ ansible_password }}"
    validate_certs: "{{ aci_validate_certs }}"
    output_level:   "{{ aci_output_level }}"
    tenant:         "{{ tenant.name }}"
    description:    "{{ tenant.description | default(omit) }}"
    state:          "{{ force_state if force_state else tenant.state | default('present') }}"
